# Generated by Django 5.1.4 on 2024-12-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('distrito', models.CharField(max_length=100)),
                ('data_hora_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('agrodealer', 'Agrodistribuidor'), ('producer', 'Produtor'), ('buyer', 'Atacadista')], max_length=20)),
                ('distrito', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localizacao', models.CharField(max_length=255)),
                ('qualidade', models.CharField(max_length=100)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='linkagro.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrevisaoColheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('quantidade_prevista', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='linkagro.produto')),
            ],
        ),
    ]
