# Generated by Django 5.1.4 on 2024-12-14 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkagro', '0003_perfilusuario_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='auth_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
