# Generated by Django 5.1.4 on 2024-12-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkagro', '0007_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='linkagro.categoria'),
        ),
    ]
