# Generated by Django 5.1.4 on 2024-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkagro', '0009_produtoimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
